In [34]:
import pandas as pd

In [35]:
df =pd.read_csv("../../datasets/employees.csv")
df.head()

   Age  Salary Department  Education     City  Experience Promoted
0   23   45000         IT  Bachelors  Nairobi           1       No
1   31   72000    Finance    Masters  Mombasa           5      Yes
2   28   58000         IT  Bachelors  Nairobi           3       No
3   42   95000         HR        PhD   Kisumu          12      Yes
4   35   68000  Marketing    Masters  Nairobi           7      Yes

## Encoding

In [36]:
from sklearn.preprocessing import OneHotEncoder
encoder=OneHotEncoder(sparse_output=False,handle_unknown='ignore',drop='first').set_output(transform='pandas')

In [37]:
ohetransform=encoder.fit_transform(df[["Department",'Education','City']])

In [38]:
ohetransform

,Department_HR,Department_IT,Department_Marketing,Education_Masters,Education_PhD,City_Kisumu,City_Mombasa,City_Nairobi,City_Nakuru
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
4,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
7,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
8,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
9,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0

## Combine the encoded cartegories with the numeric features

In [39]:
from sklearn.compose import ColumnTransformer

In [43]:
preprocessor=ColumnTransformer(
    transformers=[
        ('cat',OneHotEncoder(sparse_output=False),['Department','Education','City'])
    ],
    remainder='passthrough'
).set_output(transform='pandas')

In [44]:
df=preprocessor.fit_transform(df)
df

,cat__Department_Finance,cat__Department_HR,cat__Department_IT,cat__Department_Marketing,cat__Education_Bachelors,cat__Education_Masters,cat__Education_PhD,cat__City_Eldoret,cat__City_Kisumu,cat__City_Mombasa,cat__City_Nairobi,cat__City_Nakuru,remainder__Age,remainder__Salary,remainder__Experience,remainder__Promoted
0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,23,45000,1,No
1,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,31,72000,5,Yes
2,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,28,58000,3,No
3,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,42,95000,12,Yes
4,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,35,68000,7,Yes
5,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,24,42000,1,No
6,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,29,61000,4,No
7,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,38,83000,9,Yes
8,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,26,50000,2,No
9,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,45,110000,18,Yes