In [1]:
import pandas as pd

In [5]:
df =pd.read_csv("../../datasets/employees.csv")
df.head()

   Age  Salary Department  Education     City  Experience Promoted
0   23   45000         IT  Bachelors  Nairobi           1       No
1   31   72000    Finance    Masters  Mombasa           5      Yes
2   28   58000         IT  Bachelors  Nairobi           3       No
3   42   95000         HR        PhD   Kisumu          12      Yes
4   35   68000  Marketing    Masters  Nairobi           7      Yes

## Encoding

In [23]:
from sklearn.preprocessing import OneHotEncoder
encoder=OneHotEncoder(sparse_output=False,handle_unknown='ignore',drop='first').set_output(transform='pandas')

In [25]:
ohetransform=encoder.fit_transform(df[["Department",'Education','City']])

In [26]:
ohetransform

,Department_HR,Department_IT,Department_Marketing,Education_Masters,Education_PhD,City_Kisumu,City_Mombasa,City_Nairobi,City_Nakuru
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
4,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
7,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
8,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
9,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0

## Combine the encoded cartegories with the numeric features

In [20]:
from sklearn.compose import ColumnTransformer

In [22]:
preprocessor=ColumnTransformer(
    transformers=[
        ('cat',OneHotEncoder(),['Department','Education','City'])
    ],
    remainder='passthrough'
)