In [1]:
import pandas as pd

In [8]:
data='../../datasets/employees.csv'
df=pd.read_csv(data)
df.head()

   Age  Salary Department  Education     City  Experience Promoted
0   23   45000         IT  Bachelors  Nairobi           1       No
1   31   72000    Finance    Masters  Mombasa           5      Yes
2   28   58000         IT  Bachelors  Nairobi           3       No
3   42   95000         HR        PhD   Kisumu          12      Yes
4   35   68000  Marketing    Masters  Nairobi           7      Yes

In [9]:
from sklearn.preprocessing import OneHotEncoder
encoder=OneHotEncoder(
    sparse_output=False,
    handle_unknown='ignore',
    drop='first'
).set_output(transform='pandas')

In [14]:
ohetransform=encoder.fit_transform(df[['City']])
ohetransform.head()

   City_Kisumu  City_Mombasa  City_Nairobi  City_Nakuru
0          0.0           0.0           1.0          0.0
1          0.0           1.0           0.0          0.0
2          0.0           0.0           1.0          0.0
3          1.0           0.0           0.0          0.0
4          0.0           0.0           1.0          0.0

In [19]:
df=pd.concat([df,ohetransform],axis=1).drop(columns=['City'])
df

,Age,Salary,Department,Education,Experience,Promoted,City_Kisumu,City_Mombasa,City_Nairobi,City_Nakuru,...,City_Nairobi,City_Nakuru,City_Kisumu,City_Mombasa,City_Nairobi,City_Nakuru,City_Kisumu,City_Mombasa,City_Nairobi,City_Nakuru
0,23.0,45000.0,IT,Bachelors,1.0,No,0.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1,31.0,72000.0,Finance,Masters,5.0,Yes,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
2,28.0,58000.0,IT,Bachelors,3.0,No,0.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
3,42.0,95000.0,HR,PhD,12.0,Yes,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,35.0,68000.0,Marketing,Masters,7.0,Yes,0.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
5,24.0,42000.0,Finance,Bachelors,1.0,No,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,29.0,61000.0,IT,Masters,4.0,No,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
7,38.0,83000.0,HR,Bachelors,9.0,Yes,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
8,26.0,50000.0,Marketing,Bachelors,2.0,No,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
9,45.0,110000.0,Finance,PhD,18.0,Yes,0.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
2,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
3,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
5,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
7,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
8,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
9,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0